### ISSUE TITLE
Sign and community release of the plugin?

### ISSUE THREAD

**Issue by phaenr** [grafana/discourse-datasource#3]
Dear grafana team,

we'd like to use this datasource within our grafana to collect reports from the discourse we are using. Currently the only option to run it is to enable unsigned plugins explicitly or fork it and sign it ourselves as a private plugin. The first option is working in general, but we are really unhappy with running unsigned plugins. 

Do you plan on signing and releasing this plugin for the community in the near future?

Best regards

**Comment by daniellee** [comment]
@phaenr yes, we do. We have been using it to track metrics for our Discourse site so need to get it signed and published it soon. Didn't know that anyone else was using it yet!

**Comment by phaenr** [comment]
Sounds great @daniellee! Do you know approximately when that will happen? We are about to launch a discourse instance to replace our old forum and would like to use it from the start. If it does take a while longer we would just use it unsigned on a temporary basis until its signed.

**Comment by daniellee** [comment]
@phaenr just finishing up a PR to add filtering by category (#4) and will publish it this week.

**Comment by daniellee** [comment]
@phaenr Signed and published v1.1.0: https://grafana.com/grafana/plugins/grafana-discourse-datasource/
